# Generated by Django 2.2 on 2019-08-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuchongwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('words', models.FloatField()),
                ('bclass', models.CharField(max_length=30)),
                ('newz', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('burl', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bookf',
            },
        ),
        migrations.CreateModel(
            name='btable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('table', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'btable',
            },
        ),
    ]
