# Generated by Django 2.2 on 2019-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuchongwo', '0002_bookf_btable'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookT',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('click', models.IntegerField()),
                ('collection', models.IntegerField()),
                ('recommend', models.IntegerField()),
            ],
        ),
    ]
