# Generated by Django 2.2 on 2019-09-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuchongwo', '0003_bookt'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
            ],
        ),
    ]
