# Generated by Django 2.2 on 2019-09-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuchongwo', '0004_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='rec_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(max_length=20)),
            ],
        ),
    ]
